package com.vahak.pc.policy.domain

import jakarta.persistence.*
import org.hibernate.annotations.UpdateTimestamp
import java.time.Instant
import java.util.UUID

@Entity
@Table(
    name = "blocked_domains",
    uniqueConstraints = [
        UniqueConstraint(columnNames = ["child_id", "domain"])
    ]
)
class BlockedDomain(
    @Id
    @Column(name = "id", updatable = false, nullable = false)
    val id: UUID, // Accepts the UUID generated by Android

    @Column(name = "child_id", nullable = false)
    val childId: UUID,

    @Column(name = "domain", nullable = false)
    val domain: String,

    @Column(name = "is_active", nullable = false)
    var isActive: Boolean = true,

    @UpdateTimestamp
    var updatedAt: Instant? = null
)